# random stucky prompt generator written by amethystkrystal
# If you end up creating fanworks based on prompt generated by this code, I would love it if you let me know!
# Please contact amethystkrystal219@gmail.com with any questions

#import random module
from random import randrange

#create file where prompts will be written
f = open("stuckyprompts.txt", "w+")

#loop for wrting multiple prompts
for i in range(900):

    #create lists of Steve & Bucky variations and tropes
    steves = ["Pre-serum", "Winter Soldier", "Captain America", "Nomad", "Retired", "Commander Rogers", "Modern"];
    buckys = ["Pre-war", "Winter Soldier", "Captain America", "Post-Civil War", "Retired", "Modern"];
    trope_list = ["bed sharing", "fake dating", "bathing", "kidfic", "hurt/comfort", "mutual pining", "soulmates",
                  "friends to lovers", "friends with benefits to lovers", "body worship",
                  "meet cute", "sickfic", "gardening", "adopting a pet", "touch starved", "letter writing", "dream sharing",
                  "cooking", "vacation", "domestic fluff"]


    f.write(steves[randrange(len(steves))] + " Steve and " + buckys[randrange(len(buckys))] + " Bucky - " + trope_list[randrange(len(trope_list))] + "\n")

f.close()
